### ISSUE TITLE
 A Request for Help

### ISSUE THREAD

**Issue by HangWu1991** [srajappa/semanticLabel#1]
could you provide me with the dataset: "cvip_image_data.mat".I am interested with semantic understanding of image. thank you very much. My e-mail: 2008.wuhang@gmail.com

**Comment by srajappa** [comment]
Hi Hang! I will be glad to help you out :+1: I am not able to find the data set as of now, but I will ask my friends for the same. Please wait up :smile:

**Comment by HangWu1991** [comment]
@srajappa Thanks again for your kindness and help. I am looking  forward to hearing from you.

**Comment by srajappa** [comment]
I just sent you an email. I hope it isn't directed to your SPAM box.

**Comment by islemm** [comment]
could you provide me with the dataset: "cvip_image_data.mat". thank you very much. My e-mail: islemislem65@gmail.com
